In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import sys
from tqdm.auto import tqdm

C:\Users\cdipt\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\cdipt\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\cdipt\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
C:\Users\cdipt\anaconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
#We cannot store the matrix but can certainly store the vectors
def m2v(func,src):
    """
    Considering square matrix for simplicity
    Function to calculate the matrix product between a matrix and vector
    func(x,y): Gives the values of the matrix at the position (x,y)
    """
    n_rows=n_cols=src.shape[0]
    dest = []
    for i in range(n_rows):
        row = np.array(list(func(i,j) for j in range(n_cols)))
        dest.append(np.dot(row,src))
    return np.array(dest)

def delta(x,y):
    if x == y:
        return 1
    else:
        return 0
    
def matrix_gen(x,y):
    return 0.5*(delta((x-1),y)+2*delta(x,y)+delta((x+1),y))

def inverse(matrix_gen,SHAPE,MAX_CONJ_GRAD_ITERS = 1000,EPS = 1e-6):
    mat = []
    for index in range(SHAPE):
        b = np.zeros((SHAPE))
        b[index] = 1
        x = np.zeros((SHAPE))
        r = b - m2v(matrix_gen,x)
        if np.sum(np.abs(r))< EPS:
            print("Solution Found !!!")
        p = r.copy()
        r_dot_old = np.dot(r,r)

        for k in range(MAX_CONJ_GRAD_ITERS):
            alpha = r_dot_old/(np.dot(p,m2v(matrix_gen,p)))
            x = x + alpha*p
            r = r - alpha*m2v(matrix_gen,p)
            if np.sum(np.abs(r))< EPS:
                mat.append(x[:,None])
                break

            beta = np.dot(r,r)/r_dot_old
            p = r + beta*p    
            r_dot_old = np.dot(r,r)
    return np.concatenate(mat,axis = -1)

In [180]:
SHAPE = 3
MAX_CONJ_GRAD_ITERS = 1000
EPS = 1e-6

In [98]:
b

array([1., 0., 0.])

array([[1. , 0.5, 0. ],
       [0.5, 1. , 0.5],
       [0. , 0.5, 1. ]])

In [151]:
 p =p+1

In [152]:
r

array([1., 0., 0.])

In [181]:
A

array([[1. , 0.5, 0. ],
       [0.5, 1. , 0.5],
       [0. , 0.5, 1. ]])

In [235]:
def inverse(matrix_gen,SHAPE,MAX_CONJ_GRAD_ITERS = 1000,EPS = 1e-6):
    mat = []
    for index in range(SHAPE):
        b = np.zeros((SHAPE))
        b[index] = 1
        x = np.zeros((SHAPE))
        r = b - m2v(matrix_gen,x)
        if np.sum(np.abs(r))< EPS:
            print("Solution Found !!!")
        p = r.copy()
        r_dot_old = np.dot(r,r)

        for k in range(MAX_CONJ_GRAD_ITERS):
            alpha = r_dot_old/(np.dot(p,m2v(matrix_gen,p)))
            x = x + alpha*p
            r = r - alpha*m2v(matrix_gen,p)
            if np.sum(np.abs(r))< EPS:
                mat.append(x[:,None])
                break

            beta = np.dot(r,r)/r_dot_old
            p = r + beta*p    
            r_dot_old = np.dot(r,r)
    return np.concatenate(mat,axis = -1)

In [4]:
m_ = inverse(matrix_gen,SHAPE=50)

In [5]:
m_

array([[ 1.96078431, -1.92156863,  1.88235294, ..., -0.11764706,
         0.07843137, -0.03921569],
       [-1.92156863,  3.84313725, -3.76470588, ...,  0.23529412,
        -0.15686275,  0.07843137],
       [ 1.88235294, -3.76470588,  5.64705882, ..., -0.35294118,
         0.23529412, -0.11764706],
       ...,
       [-0.11764706,  0.23529412, -0.35294118, ...,  5.64705882,
        -3.76470588,  1.88235294],
       [ 0.07843137, -0.15686275,  0.23529412, ..., -3.76470588,
         3.84313725, -1.92156863],
       [-0.03921569,  0.07843137, -0.11764706, ...,  1.88235294,
        -1.92156863,  1.96078431]])

In [6]:
np.linalg.inv(A)

array([[ 1.96078431, -1.92156863,  1.88235294, ..., -0.11764706,
         0.07843137, -0.03921569],
       [-1.92156863,  3.84313725, -3.76470588, ...,  0.23529412,
        -0.15686275,  0.07843137],
       [ 1.88235294, -3.76470588,  5.64705882, ..., -0.35294118,
         0.23529412, -0.11764706],
       ...,
       [-0.11764706,  0.23529412, -0.35294118, ...,  5.64705882,
        -3.76470588,  1.88235294],
       [ 0.07843137, -0.15686275,  0.23529412, ..., -3.76470588,
         3.84313725, -1.92156863],
       [-0.03921569,  0.07843137, -0.11764706, ...,  1.88235294,
        -1.92156863,  1.96078431]])

In [3]:
SHAPE = 50
A = np.zeros((SHAPE,SHAPE))
for i in range(SHAPE):
    for j in range(SHAPE):
        A[i,j] = matrix_gen(i,j)

array([[0.25,  nan,  nan],
       [0.25,  nan,  nan]])

In [17]:
row = np.array(list(matrix_gen(3,j) for j in range(5)))

In [18]:
row.shape

(5,)

In [19]:
np.dot(row,row)

1.5